version: '3.8'

# This section defines the services (containers) for your application
services:

  # MySQL Database Service
  mysql-db:
    container_name: mysql-db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  # MongoDB Database Service
  mongodb-db:
    container_name: mongodb-db
    image: mongo:6.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - "27018:27017"
    volumes:
      - mongodb-data:/data/db

  # Your Application Service
  app:
    container_name: nest-app
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mysql-db
      - mongodb-db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules # Prevents host's node_modules from overwriting container's
    environment:
      # Use the service names from this file for the hosts
      MYSQL_HOST: mysql-db
      MYSQL_PORT: 3306
      MONGO_HOST: mongodb-db
      MONGO_PORT: 27017

    command: sh -c "npm run migration:run && npm run seed:run && npm run build && npm run start:prod"
# This section defines named volumes for persistent data
volumes:
  mysql-data:
  mongodb-data: